apiVersion: v1
kind: Pod
metadata:
  name: mywebapp5
  labels:
    class: unnati
spec:
  containers:
    - name: web
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
